package dna.io.filesystem;

/**
 * Suffixes for various files written as output / result data.
 * 
 * @author benni
 * 
 */
public class Suffix {
	// graph as written by GraphWriter and read by GraphReader
	public static final String graph = ".graph";

	// batch as written by BatchWriter and read by BatchReader
	public static final String batch = ".batch";

	// distribution as generated by a metric
	public static final String distribution = ".distribution";

	// nodevaluelist as generated by a metric
	public static final String nodeValueList = ".nodevaluelist";

	// gnuplot script generated by the plotting wrapper
	public static final String gnuplot = ".gnuplot";

	// data files used by gnuplot
	public static final String data = ".data";

	// list of values (ValueList)
	public static final String values = ".values";

	// list of runtimes (RunTimeList)
	public static final String runtimes = ".runtimes";

	// suffix for quality metrics
	public static final String quality = ".quality";

	// suffix for exact metrics
	public static final String exact = ".exact";

	// suffix for heuristical metrics
	public static final String heuristic = ".heuristic";
}
