package dna.settings;

public class Suffix {
	// distribution as generated by a metric
	public static final String distribution = ".distribution";
	
	// gnuplot script generated by the plotting wrapper
	public static final String gnuplot = ".gnuplot";
	
	// data files used by gnuplot
	public static final String data = ".data";
	
	// list of values (ValueList)
	public static final String values = ".values";
	
	// list of runtimes (RunTimeList)
	public static final String runtimes = ".runtimes";
}
