package dna.graph.nodes.zalando;

import dna.graph.generators.GraphGenerator;
import dna.graph.generators.zalando.EventColumn;
import dna.updates.generators.BatchGenerator;

/**
 * This interface specifies additional information for nodes generated by
 * Zalando {@link GraphGenerator}s and {@link BatchGenerator}s. This additional
 * information is mandatory if (parts of) the original data should be accessible
 * in the final graph.
 */
public interface IZalandoNode {

	/**
	 * @return The {@link EventColumn}s of the value represented by this node.
	 *         May be e.g. {@code [PERMANENT_COOKIE_ID]} if a node represents
	 *         one customer or {@code [PERMANENT_COOKIE_ID, ACTION]} if a node
	 *         represents a customer's action.
	 */
	public EventColumn[] getType();

}
